### ISSUE TITLE
Location blueprint broken: Location not saving and does not display after saving

### ISSUE THREAD

**Issue by robertschnuell** [medienhaus/medienhaus-cms#186]
1. Create an item
2. Add Location
3. Marker not showing up (sometimes)
4. Location Save shows roomId = undifined in Console (sometimes)
5. if saving works, does not show saved location instead just the '🎭' emoji

for reproduction: standart config and .env file without an api.

**Comment by marcel-klasse** [comment]
cannot reproduce marker error, seems to be a local problem.

**Comment by fnwbr** [comment]
I just fixed the marker not showing up: https://github.com/medienhaus/medienhaus-cms/commit/d6e4e96dc74b0d7477ac09c90ac9c2fc0efa2568

This only happens when the CMS does not live in the root directory of your webspace, but in a sub-directory instead.

@robertschnuell To fix your current deployment make sure you set these two `.env` variables accordingly: https://github.com/medienhaus/medienhaus-cms/commit/d6e4e96dc74b0d7477ac09c90ac9c2fc0efa2568#diff-84fba1a01bc93994b7f2ed668192b6d0c9f6815ded540b67b29698ca539ce4d2R3-R4
