### ISSUE TITLE
`/create` Gutenberg `Heading` blocktype h3 by default

### ISSUE THREAD

**Issue by robertschnuell** [medienhaus/medienhaus-cms#210]
in general it would be nice to have different types of headings, like h1, h2, h3…, but a different feature request. anyway all blocks with the type `heading` are saved in matrix with an markdown `###` prefix. as the `template` of this space is already a `heading` there is no need to add a markdown prefix. as well as it does not make sense that it is always h3. therefore I would suggest to save it as plain text and defining the meaning of the content via the `template` only.

**Comment by marcel-klasse** [comment]
I agree, we should definitely offer multiple headings (h1-h6).  
Atm our only heading is `h2`, according to the gutenberg block https://github.com/medienhaus/medienhaus-cms/blob/498fc9c077557048a7afc7ca031a89d8a4c2345a/src/routes/gutenberg/blocks/heading.js#L39-L46 
We should probably also display it as such in the icon since it's causing confusion, I think our reasoning was there only being one heading, therefore no need for the level.

We save it as `h3`, though:
https://github.com/medienhaus/medienhaus-cms/blob/498fc9c077557048a7afc7ca031a89d8a4c2345a/src/routes/create/index.js#L386-L392

I will change it to match `h3` in the gutenberg block. 

Regarding markdown: IIRC we adopted [element's](https://github.com/vector-im/element-web) convention of saving markdown formatted text in the `body` key. I think if we change this we should change it for all messages, not just for headings. It's probably worth having a look at different clients before we do this, so our saved messages get displayed correctly in most of them.
